### PR TITLE
feat: :sparkles: add nnf to footer with link

### PR DESCRIPTION
**Pull request by signekb**
## Description

- This PR adds NNF to the website footer with a link to the "Acknowledgement" section in `index.qmd` (which doesn't exist yet, but will be added in a PR later today). EDIT: #257 

## Related Issues

See also Issues #116

### CODE REVIEW

**Review by K-Beicher — APPROVED** [review]
Looks good on screen as well.

**Comment by signekb** [comment]
@lwjohnst86 Should this actually be added to the `theme` instead?

**Comment by lwjohnst86** [comment]
I'll merge this in when the other PR is opened and merged :)

**Comment by signekb** [comment]
Alrighty. I have now opened the PR #257

**Pull request merged**
